services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ###################
  # Основные сервисы
  ###################

  # Генератор элементов кастомных таблиц.
  bitrix_database_bundle.fixture_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\FixtureGenerator
    arguments: [!tagged_locator { tag: 'fixture_generator.item' }, '%bitrix_database_bundle_fixture_path%']

  # Генератор элементов и разделов инфоблока.
  bitrix_database_bundle.element_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\IblockDataGenerator
    arguments:
      - !tagged_locator { tag: 'fixture_generator.item' }
      - '@bitrix_database_bundle.standart_element_mapper'
      - '@bitrix_database_bundle.iblock_sections_manager'
      - '%bitrix_database_bundle_fixture_path%'

  # Генератор элементов hl-инфоблока.
  bitrix_database_bundle.hl_element_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\IblockHlDataGenerator
    arguments:
      - !tagged_locator { tag: 'fixture_generator.item' }
      - '@bitrix_database_bundle.standart_element_mapper'
      - '@bitrix_database_bundle.hl_manager'
      - '%bitrix_database_bundle_fixture_path%'

  ##############
  # Инструменты
  ##############

  # Битриксовый CIBlockPropertyEnum
  bitrix_database_bundle.bitrix_property_enums:
    class: CIBlockPropertyEnum

  # Обработчики полей элементов и подразделов по умолчанию.
  bitrix_database_bundle.standart_element_mapper:
    class: Local\Bundles\BitrixDatabaseBundle\Services\StandartIblockDataMapper

  # Удаление элементов.
  bitrix_database_bundle.iblock_element_eraser:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\TruncaterElements
    arguments: ['@CIBlockElement', '@CFile']

  # Менеджер подразделов.
  bitrix_database_bundle.iblock_sections_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\IblockSections
    arguments: ['@CIBlockSection']

  # Менеджер high-load блоков.
  bitrix_database_bundle.hl_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\HighloadBlock

  # Менеджер свойств инфоблоков.
  bitrix_database_bundle.iblock_properties_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\IblockProperties
    arguments: ['@bitrix_database_bundle.bitrix_property_enums']

  # Заполнение кастомной таблицы тестовыми данными.
  bitrix_database_bundle.seeder_db:
    class: Local\Bundles\BitrixDatabaseBundle\Services\SeedDatabase
    arguments: [!tagged_locator { tag: 'bitrix_custom_table' }]

  ##########
  # Команды
  ##########

  # Наполнение таблицы фикстурой.
  bitrix_database_bundle.command_seed_database:
    class: Local\Bundles\BitrixDatabaseBundle\Command\SeedDatabaseCommand
    arguments:
        - '@bitrix_database_bundle.fixture_generator'
        - '@bitrix_database_bundle.seeder_db'
        - !tagged_locator { tag: 'bitrix_custom_table' }
    tags:
      - { name: console.command, comand: migrator:seed }

  # Команда создания структуры проекта.
  bitrix_database_bundle.command_create_structure:
    class: Local\Bundles\BitrixDatabaseBundle\Command\StructureCreatorRunner
    arguments: ['%bitrix_database_bundle_test_project%']
    tags:
      - { name: console.command, comand: migrator:structure }

  # Наполнение инфоблока элементами.
  bitrix_database_bundle.command_seed_elements:
    class: Local\Bundles\BitrixDatabaseBundle\Command\SeedElementsCommand
    arguments:
      - '@bitrix_database_bundle.element_generator'
      - '@bitrix_database_bundle.iblock_element_eraser'
    tags:
      - { name: console.command, comand: migrator:elements }

  # Наполнение hl-инфоблока элементами.
  bitrix_database_bundle.command_seed_hl_elements:
    class: Local\Bundles\BitrixDatabaseBundle\Command\SeedHlElementsCommand
    arguments:
      - '@bitrix_database_bundle.hl_element_generator'
      - '@bitrix_database_bundle.hl_manager'
    tags:
      - { name: console.command, comand: migrator:elements-hl }
