services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ###################
  # Основные сервисы
  ###################

  # Генератор элементов кастомных таблиц.
  bitrix_database_bundle.fixture_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\FixtureGenerator
    arguments: [!tagged_locator { tag: 'fixture_generator.item' }, '@bitrix_database_bundle.fixture_resolver']

  # Генератор элементов и разделов инфоблока.
  bitrix_database_bundle.element_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\IblockDataGenerator
    arguments:
      - !tagged_locator { tag: 'fixture_generator.item' }
      - '@bitrix_database_bundle.standart_element_mapper'
      - '@bitrix_database_bundle.default_properties_processor'
      - '@bitrix_database_bundle.iblock_sections_manager'
      - '@bitrix_database_bundle.fixture_resolver'
      - '%bitrix_database_bundle_ignore_errors%'

  # Генератор элементов hl-инфоблока.
  bitrix_database_bundle.hl_element_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\IblockHlDataGenerator
    arguments:
      - !tagged_locator { tag: 'fixture_generator.item' }
      - '@bitrix_database_bundle.default_properties_processor'
      - '@bitrix_database_bundle.hl_manager'
      - '@bitrix_database_bundle.fixture_resolver'
      - '%bitrix_database_bundle_ignore_errors%'

  # Генератор пользователей.
  bitrix_database_bundle.users_generator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\UserGenerator
    arguments:
      - '@bitrix_database_bundle.bitrix_cuser'
      - '@bitrix_database_bundle.bitrix_cgroup'

  ##############
  # Инструменты
  ##############

  # Битриксовый CIBlockPropertyEnum
  bitrix_database_bundle.bitrix_property_enums:
    public: false
    class: CIBlockPropertyEnum

  # Битриксовый CUSER.
  bitrix_database_bundle.bitrix_cuser:
    public: false
    class: CUser

  # Битриксовый CGroup.
  bitrix_database_bundle.bitrix_cgroup:
    public: false
    class: CGroup

  # Обработчики полей элементов и подразделов по умолчанию.
  bitrix_database_bundle.standart_element_mapper:
    class: Local\Bundles\BitrixDatabaseBundle\Services\StandartIblockDataMapper

  bitrix_database_bundle.default_properties_processor:
    class: Local\Bundles\BitrixDatabaseBundle\Services\DefaultPropertiesValueProcessor
    arguments:
      - '@bitrix_database_bundle.iblock_properties_manager'

  # Удаление элементов.
  bitrix_database_bundle.iblock_element_eraser:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\TruncaterElements
    arguments: ['@CIBlockElement', '@CFile']

  # Менеджер подразделов.
  bitrix_database_bundle.iblock_sections_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\IblockSections
    arguments: ['@CIBlockSection']

  # Менеджер high-load блоков.
  bitrix_database_bundle.hl_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\HighloadBlock

  # Менеджер свойств инфоблоков.
  bitrix_database_bundle.iblock_properties_manager:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Iblocks\IblockProperties
    arguments: ['@bitrix_database_bundle.bitrix_property_enums']

  # Заполнение кастомной таблицы тестовыми данными.
  bitrix_database_bundle.seeder_db:
    class: Local\Bundles\BitrixDatabaseBundle\Services\SeedDatabase
    arguments: [!tagged_locator { tag: 'bitrix_custom_table' }]

  bitrix_database_bundle.finder_files:
    class: Symfony\Component\Finder\Finder

 # Локатор классов-фикстур.
  bitrix_database_bundle.fixture_class_locator:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Utils\FixtureClassLocator
    arguments: ['@bitrix_database_bundle.finder_files', '%bitrix_database_bundle_fixture_path%']

  # Комплексный загрузчик фикстур.
  bitrix_database_bundle.fixture_resolver:
    class: Local\Bundles\BitrixDatabaseBundle\Services\Utils\FixtureResolver
    arguments:
        - '@bitrix_database_bundle.fixture_class_locator'
        - '@annotations.reader'
        - '%bitrix_database_bundle_fixture_path%'
