services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Валидатор Symfony
  custom_arguments_resolvers.validator:
    public: false
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: ['Symfony\Component\Validator\Validation', 'createValidator']

  # Валидатор запроса.
  custom_arguments_resolvers.validator_request:
    public: false
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\Validator\RequestAnnotationValidator
    arguments:
      - '@annotations.cached_reader'
      - '@custom_arguments_resolvers.validator'
      - '@serializer'

  Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\Validator\RequestAnnotationValidatorInterface: '@custom_arguments_resolvers.validator_request'

  # Request в DTO.
  # Важно: priority должно быть установлено как можно больше,
  # иначе все зашибает симфонический ServiceValueResolver и до этого ресолвера
  # дело не доходит.
  custom_arguments_resolvers.unserialize_request:
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\RequestBodyArgumentResolver
    arguments:
      - '@annotations.cached_reader'
      - '@Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver'
      - '@serializer'
      - '@custom_arguments_resolvers.validator_request'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }


  # $_GET параметры в DTO.
  custom_arguments_resolvers.query_params:
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\QueryParamsArgumentResolver
    arguments:
      - '@annotations.cached_reader'
      - '@Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver'
      - '@serializer'
      - '@custom_arguments_resolvers.validator_request'
      - '@property_info'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }

  # $_POST параметры в DTO.
  custom_arguments_resolvers.post_params:
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\RequestParamArgumentResolver
    arguments:
      - '@annotations.cached_reader'
      - '@Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver'
      - '@serializer'
      - '@custom_arguments_resolvers.validator_request'
      - '@property_info'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }

  # Bitrix file.
  custom_arguments_resolvers.bitrix_file:
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\BitrixFileArgumentResolver
    arguments:
      - '@annotations.cached_reader'
      - '@Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }

  # Bitrix file url.
  custom_arguments_resolvers.bitrix_file_url:
    class: Local\Bundles\CustomArgumentResolverBundle\ArgumentsResolver\BitrixFileUrlArgumentResolver
    arguments:
      - '@annotations.cached_reader'
      - '@Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }
