services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Разрешитель зависимостей.
  custom_arguments_resolvers.resolver:
    class: Local\Bundles\CustomArgumentResolverBundle\Service\ResolversDependency\ResolveDependencyMaker

  Local\Bundles\CustomArgumentResolverBundle\Service\ResolversDependency\ResolveDependencyMaker: '@custom_arguments_resolvers.resolver'

  # Разрешитель зависимостей с учетом контейнера.
  custom_arguments_resolvers.container.aware.resolver:
    class: Local\Bundles\CustomArgumentResolverBundle\Service\ResolversDependency\ResolveDependencyMakerContainerAware
    calls:
      - setContainer: ['@service_container']

  Local\Bundles\CustomArgumentResolverBundle\Service\ResolversDependency\ResolveDependencyMakerContainerAware: '@custom_arguments_resolvers.container.aware.resolver'

  custom_arguments_resolvers.controller_argument.processor:
    class: Local\Bundles\CustomArgumentResolverBundle\Event\InjectorController\CustomArgumentResolverProcessor
    arguments:
      - '@custom_arguments_resolvers.container.aware.resolver'
      - '@custom_arguments_resolvers.ignored.autowiring.controller.arguments'
    calls:
      - setContainer: ['@service_container']

  Local\Bundles\CustomArgumentResolverBundle\Event\InjectorController\CustomArgumentResolverProcessor: '@custom_arguments_resolvers.controller_argument.processor'
  Local\Bundles\CustomArgumentResolverBundle\Event\InjectorController\InjectorControllerInterface: '@custom_arguments_resolvers.controller_argument.processor'

  custom_arguments_resolvers.resolver.from.container:
    class: Local\Bundles\CustomArgumentResolverBundle\Service\Utils\ResolveParamsFromContainer
    calls:
      - setContainer: ['@service_container']

  Local\Bundles\CustomArgumentResolverBundle\Service\Utils\ResolveParamsFromContainer: '@custom_arguments_resolvers.resolver.from.container'

  # Игнорируемые при автовайринге классы (учитывя наследование).
  custom_arguments_resolvers.ignored.autowiring.controller.arguments:
    class: Local\Bundles\CustomArgumentResolverBundle\Service\Utils\IgnoredAutowiringControllerParamsBag
    calls:
      - add: [['Local\Bundles\ApiDtoConvertorBundle\DependencyInjection\BaseDTOInterface', 'Spatie\DataTransferObject\DataTransferObject']]

  Local\Bundles\CustomArgumentResolverBundle\Service\Utils\IgnoredAutowiringControllerParamsBag: '@custom_arguments_resolvers.ignored.autowiring.controller.arguments'

  custom_arguments_resolvers.security.csrf.token_manager:
    class: Symfony\Component\Security\Csrf\CsrfTokenManager

  # Проверка CSRF токена.
  custom_arguments_resolvers.csrf_checker:
    class: Local\Bundles\CustomArgumentResolverBundle\Service\Utils\CsrfRequestHandler
    arguments:
      - '@custom_arguments_resolvers.security.csrf.token_manager'
      - '@parameter_bag'
