_common:
  resource: staticPages/statics.yaml

foo_route:
  path: /api/foo/
  controller: 'Local\SymfonyTools\Router\Examples\DummyController::action'

foo_placeholder_route:
  path: /api/foo/{id}/
  controller: 'Local\SymfonyTools\Router\Examples\DummyController::loadAction'
  requirements:
    id: "[0-9]+"
