<?php

return [
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Local\Bundles\CustomArgumentResolverBundle\CustomArgumentResolverBundle::class => ['all' => true],
    // Local\Bundles\ApiDtoConvertorBundle\ApiDtoConvertorBundle::class => ['all' => true],
    Prokl\GuzzleBundle\CsaGuzzleBundle::class => ['all' => true],
    Local\Bundles\SymfonyMiddlewareBundle\MiddlewareBundle::class => ['all' => true],
    Local\Bundles\TaskSchedulerBundle\RewieerTaskSchedulerBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['all' => true],
    Prokl\BundleMakerBundle\BundleMakerBundle::class => ['all' => true],
    Prokl\StaticPageMakerBundle\StaticPageMakerBundle::class => ['all' => true],
    Local\Bundles\ModelBundle\ModelBundle::class => ['all' => true],
    Prokl\BitrixWebformBundle\BitrixWebformBundle::class => ['all' => true],
    Prokl\BitrixFormBundle\BitrixFormBundle::class => ['all' => true],
    Prokl\ApiExceptionBundle\M6WebApiExceptionBundle::class => ['all' => true],
    Local\Bundles\BitrixIblockElementValidatorBundle\BitrixIblockElementValidatorBundle::class => ['all' => true],
    Local\Bundles\UrlSignedBundle\UrlSignedBundle::class => ['all' => true],
    Prokl\BitrixOgGraphBundle\BitrixOgGraphBundle::class => ['all' => true],
    Local\Bundles\InstagramParserRapidApiBundle\InstagramParserRapidApiBundle::class => ['all' => true],
    AutoMapperPlus\AutoMapperPlusBundle\AutoMapperPlusBundle::class => ['all' => true],
    Local\Bundles\DtoMapperBundle\DtoMapperBundle::class => ['all' => true],
    Local\Bundles\BitrixComponentParamsBundle\BitrixComponentParamsBundle::class => ['all' => true],
    Local\Bundles\SymfonyMailerBundle\SymfonyMailerBundle::class => ['all' => true],
    Local\Bundles\RequestLogBundle\RequestLogBundle::class => ['all' => true],
    Prokl\SymfonyBladeBundle\SymfonyBladeBundle::class => ['all' => true],
    // Local\Bundles\BitrixUtilsBundle\BitrixUtilsBundle::class => ['all' => true],
    Prokl\RequestValidatorBundle\RequestValidatorBundle::class => ['all' => true],
    Local\Bundles\BitrixDatabaseBundle\BitrixDatabaseBundle::class => ['all' => true],
    Local\Bundles\FrameworkExtensionBundle\FrameworkExtensionBundle::class => ['all' => true],
    Prokl\FacadeBundle\FacadeBundle::class => ['all' => true],
    Prokl\CkEditorBundle\CkEditorBundle::class => ['all' => true],
    Prokl\AnnotatedParamResolverBundle\AnnotatedParamResolverBundle::class => ['all' => true],
    Prokl\BitrixAnnotatedResolversBundle\BitrixAnnotatedResolversBundle::class => ['all' => true],
    Prokl\BitrixSymfonyRouterBundle\SymfonyRouterBundle::class => ['all' => true],
    Prokl\CollectionExtenderBundle\CollectionExtenderBundle::class => ['all' => true],
];
