<?php

return [
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Local\Bundles\CustomArgumentResolverBundle\CustomArgumentResolverBundle::class => ['all' => true],
    Local\Bundles\ApiExceptionBundle\M6WebApiExceptionBundle::class => ['all' => true],
    // Local\Bundles\ApiDtoConvertorBundle\ApiDtoConvertorBundle::class => ['all' => true],
    Local\Bundles\GuzzleBundle\CsaGuzzleBundle::class => ['all' => true],
    Local\Bundles\SymfonyMiddlewareBundle\MiddlewareBundle::class => ['all' => true],
    Local\Bundles\TaskSchedulerBundle\RewieerTaskSchedulerBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['all' => true],
    Local\Bundles\BundleMakerBundle\BundleMakerBundle::class => ['all' => true],
    Local\Bundles\StaticPageMakerBundle\StaticPageMakerBundle::class => ['all' => true],
    Local\Bundles\ModelBundle\ModelBundle::class => ['all' => true],
    Local\Bundles\BitrixWebformBundle\BitrixWebformBundle::class => ['all' => true],
    Local\Bundles\BitrixCustomPropertiesBundle\BitrixCustomPropertiesBundle::class => ['all' => true],
    Local\Bundles\BitrixIblockElementValidatorBundle\BitrixIblockElementValidatorBundle::class => ['all' => true],
    Local\Bundles\UrlSignedBundle\UrlSignedBundle::class => ['all' => true],
    Local\Bundles\BitrixOgGraphBundle\BitrixOgGraphBundle::class => ['all' => true],
    Local\Bundles\InstagramParserRapidApiBundle\InstagramParserRapidApiBundle::class => ['all' => true],
    AutoMapperPlus\AutoMapperPlusBundle\AutoMapperPlusBundle::class => ['all' => true],
    Local\Bundles\DtoMapperBundle\DtoMapperBundle::class => ['all' => true],
    Local\Bundles\BitrixComponentParamsBundle\BitrixComponentParamsBundle::class => ['all' => true],
    Local\Bundles\SymfonyMailerBundle\SymfonyMailerBundle::class => ['all' => true],
    Local\Bundles\RequestLogBundle\RequestLogBundle::class => ['all' => true],
    Local\Bundles\SymfonyBladeBundle\SymfonyBladeBundle::class => ['all' => true],
    // Local\Bundles\BitrixUtilsBundle\BitrixUtilsBundle::class => ['all' => true],
    Local\Bundles\RequestValidatorBundle\RequestValidatorBundle::class => ['all' => true],
];
