services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  mailer.transport_factory.gmail:
    public: true
    autowire: true
    autoconfigure: false
    class: Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory
    parent: mailer.transport_factory.abstract
    tags:
      - { name: mailer.transport_factory }

  mailer.filesystem:
    public: false
    class: Symfony\Component\Filesystem\Filesystem

  # Кастомная фабрика транспортов файловой системы.
  mailer.transport_factory.filesystem:
    public: true
    class: Local\Bundles\SymfonyMailerBundle\Services\Transport\FileTransport
    arguments:
          - '%kernel.project_dir%/'
          - '@mailer.filesystem'
          - []
          - '@event_dispatcher'
          - '@logger'
    tags:
      - { name: mailer.transport_factory }

  mailer.transport_factory.smtp:
    public: true
    autowire: true
    autoconfigure: false
    class: Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory
    parent: "mailer.transport_factory.abstract"
    tags:
      - { name: mailer.transport_factory, priority: -100 }
