services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ############
  # Транспорт
  ############
  instagram_parser_rapid_api.transport:
    public: false
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\Transport\CurlTransportRapidApi
    arguments: ['%instagram_parser_rapid_api.rapid_api_key%']

  ############
  # PSR кэшер
  ############
  instagram_parser_rapid_api.cacher:
    public: false
    class: WebArch\BitrixCache\AntiStampedeCacheAdapter
    arguments: ['/', '%instagram_parser_rapid_api.cache_ttl%', '%instagram_parser_rapid_api.cache_path%']

  # Данные пользователя. Кэшируется на год!
  instagram_parser_rapid_api.cacher_user:
    public: false
    class: WebArch\BitrixCache\AntiStampedeCacheAdapter
    arguments: ['/', '%instagram_parser_rapid_api.cache_user_data_ttl%', '%instagram_parser_rapid_api.cache_path%']

  # Транспорт, обращающийся к rapidAPI.
  instagram_parser_rapid_api.rapid_api:
    public: false
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\RetrieverInstagramDataRapidApi
    arguments:
      - '@instagram_parser_rapid_api.cacher'
      - '@instagram_parser_rapid_api.transport'
      - '%instagram_parser_rapid_api.instagram_user_id%'
    calls:
      - setUseMock: ['%instagram_parser_rapid_api.mock%', '%instagram_parser_rapid_api.fixture_response_path%']


  # Получение user ID по имени пользователя.
  instagram_parser_rapid_api.rapid_api_get_user_id:
    public: true
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\UserInfoRetriever
    arguments:
      - '@instagram_parser_rapid_api.cacher_user'
      - '@instagram_parser_rapid_api.transport'
    calls:
      - setUserName: ['%instagram_parser_rapid_api.instagram_user_name%']
      - setUseMock: ['%instagram_parser_rapid_api.mock%', '%instagram_parser_rapid_api.fixture_user_path%']

  Local\Bundles\InstagramParserRapidApiBundle\Services\UserInfoRetriever: '@instagram_parser_rapid_api.rapid_api_get_user_id'

  # Трансформер данных, получаемых из rapidAPI.
  instagram_parser_rapid_api.data_transformer:
    public: false
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\InstagramDataTransformerRapidApi

  Local\Bundles\InstagramParserRapidApiBundle\Services\InstagramDataTransformerRapidApi: '@instagram_parser_rapid_api.data_transformer'

  # Оркестратор парсера.
  instagram_parser_rapid_api.parser:
    public: true
    class: Local\Bundles\InstagramParserRapidApiBundle\Services\ComplexParser
    arguments: ['@instagram_parser_rapid_api.rapid_api', '@instagram_parser_rapid_api.data_transformer']
    calls:
      - setCount: [3]

  Local\Bundles\InstagramParserRapidApiBundle\Services\ComplexParser: '@instagram_parser_rapid_api.parser'

  #####################
  # Консольные команды
  ####################

  # Создать фикстуры.
  Local\Bundles\InstagramParserRapidApiBundle\Command\MakeFixtures:
    public: true
    arguments:
      - '@instagram_parser_rapid_api.rapid_api'
      - '@instagram_parser_rapid_api.rapid_api_get_user_id'
      - '%instagram_parser_rapid_api.instagram_user_name%'
      - '%instagram_parser_rapid_api.fixture_response_path%'
      - '%instagram_parser_rapid_api.fixture_user_path%'
    tags:
      - { name: console.command, command: make:instagram-fixtures }
