# Пример рендеринга простой статической страницы прямо из роута.
simple_static_page:
  path: /simple_page/
  methods: [GET]
  controller: 'Prokl\StaticPageMakerBundle\Services\TemplateControllerContainerAware::templateAction'
  defaults:
    template:  './static/example2.twig'
    context:
      url: /simple_page/
      # Препроцессоры контекста.
      _processors:
        - '@Prokl\StaticPageMakerBundle\Services\ContextProcessors\ExampleContextProcessor'
      # Сервис как параметр
      options: '@app.options'
      site_name: 'Example site'
      object:
        errored: true
        finished: true
        pending: true
      page_type: 'static-page'
      title: 'Простая статическая страница'
      description: 'Простая статическая страница'
