bitrix-fixture-generator:
  # Игнорировать ошибки при создании элементов - сохранение картинок итд.
  ignore_errors: true

  # Пути к фикстурам.
  fixture_path:
    - '/local/classes/BaseFixtures/'

  # Набор команд, генерирующих нужную фикстуру.
  structure_project:
    - migrator:elements spravochnik content --truncate=true --sections=false --count=20
    - migrator:elements common content --truncate=true --sections=true --count=5
    - migrator:elements-hl ExampleHighload --truncate=true --count=5
