csa_guzzle:
  default_client: ~
  clients:
    example:
      # middleware: ['!cache']
      alias: ~
      config: # you can specify the options as in http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
        base_uri: https://sample.api.ru
        timeout: 2.0
        headers:
          User-Agent: testing/1.0
          Accept: application/json

  cache:
    enabled: true
    adapter: bitrix.psr.simple.cacher.adapter

  logger:
    enabled: false
    # service: ~
    service: 'logger'
    format: '{hostname} {req_header_User-Agent} - [{date_common_log}] "{method} {target} HTTP/{version}" {code} {res_header_Content-Length}'
    level: debug
  mock:
    enabled: false
    storage_path: "%kernel.project_dir%/tests/Fixtures/guzzle"
#    mode: record
    mode: replay
    request_headers_blacklist: []
    response_headers_blacklist: []
