static_page_maker:
  # ID инфоблока, где хранится сео информация по страницам.
  # NAME => URL без домена статической страницы.
  # Если равно 0 - механизм не используется.
  seo_iblock_id: 0
  set_last_modified_header: true
