twig_extension_pack:
  globals:
    secret_key: 'xxxx'
    # Отсылка к переменной сервис-провайдера.
    kernel.debug: '%kernel.debug%'
    path_build: 'webpack.build.path'
    # Сервисы указывать без @ - иначе не компилируется контейнер.
    app: 'native.app.twig.variable'

