services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Событие запуска отложенных событий по kernel.terminate.
  framework_extension.flush_delayed_events_listener:
    class: Local\Bundles\FrameworkExtensionBundle\Event\FlushDelayedEventsListener
    arguments:
      - '@delayed.event.dispatcher'
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, method: handle, priority: -100 }
