services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Исполнение отложенных событий.
  delayed.event.dispatcher:
    class: Local\Bundles\FrameworkExtensionBundle\Services\DelayedEvents\DelayedEventDispatcher
    arguments:
      - '@event_dispatcher'
      - false
      - '@framework_extension_bundle.default_delay_arbiter'
      - '@framework_extension_bundle.default_exception_handler'

  Local\Bundles\FrameworkExtensionBundle\Services\DelayedEvents\DelayedEventDispatcher: '@delayed.event.dispatcher'

  # Delay arbiter по умолчанию.
  framework_extension_bundle.default_delay_arbiter:
    class: Local\Bundles\FrameworkExtensionBundle\Services\DelayedEvents\DefaultDelayArbiter

  # Обработчик исключений по умолчанию.
  framework_extension_bundle.default_exception_handler:
    class: Local\Bundles\FrameworkExtensionBundle\Services\DelayedEvents\DefaultDelayedEventExceptionHandler
