parameters:
  # Путь, куда лягут готовые DTO
  path_ready_dto: /local/classes/Bundles/BitrixComponentParamsBundle/DTO
  # Путь, где лежат массивы-заготовки.
  path_arrays: /local/classes/Bundles/BitrixComponentParamsBundle/Services/Arrays

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Загрузчик Твига.
  bitrix_component_params_bundle.twig_loader:
    public: false
    class: Twig_Loader_Filesystem
    arguments: ['%kernel.project_dir%/local/classes/Bundles/BitrixComponentParamsBundle/Twig/Templates/']

  # Локальный экземпляр Твига.
  bitrix_component_params_bundle.twig:
    public: false
    class: Twig_Environment
    arguments:
     - '@bitrix_component_params_bundle.twig_loader'
     - [ debug: '%debug%', cache: '%kernel.project_dir%/bitrix/cache/twig']

  # Видоизмененный фильтр Твига join.
  bitrix_component_params_bundle.twig_assocjoin:
    public: false
    class: Local\Bundles\BitrixComponentParamsBundle\Twig\JoinExtension
    tags:
      - { name: local.twig.extensions }

  # Твиг - проверка на число.
  bitrix_component_params_bundle.twig_is_numeric:
    public: false
    class: Local\Bundles\BitrixComponentParamsBundle\Twig\NumericExtension
    tags:
      - { name: local.twig.extensions }

  # Команда создания DTO из массива.
  Local\Bundles\BitrixComponentParamsBundle\Command\CreateNewsDTOCommand:
    public: true
    arguments:
          - '@bitrix_component_params_bundle.twig'
          - !tagged_locator { tag: 'local.twig.extensions', index_by: 'key' }
          - '%path_ready_dto%'
          - '%path_arrays%'
    tags:
      - { name: console.command, command: dto:create }

  # DTO для комплексных компонентов news.
  bitrix_component_params_bundle.news_dto:
    public: false
    class: Local\Bundles\BitrixComponentParamsBundle\DTO\DtoNews

  # DTO для компонентов news.list.
  bitrix_component_params_bundle.news_list_dto:
    public: false
    class: Local\Bundles\BitrixComponentParamsBundle\DTO\DtoNewsList

  # Создание массива параметров для комплексных компонентов news.
  bitrix_component_params_bundle.news_arparams:
    public: true
    class: Local\Bundles\BitrixComponentParamsBundle\Services\MakeArParams
    arguments: ['@bitrix_component_params_bundle.news_dto']

  # Создание массива параметров для компонентов news.list.
  bitrix_component_params_bundle.news_list_arparams:
    public: true
    class: Local\Bundles\BitrixComponentParamsBundle\Services\MakeArParams
    arguments: ['@bitrix_component_params_bundle.news_list_dto']
