services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Local\Bundles\RequestLogBundle\Service\BitrixBridge\ResponseTransformer:
    class: Local\Bundles\RequestLogBundle\Service\BitrixBridge\ResponseTransformer
    arguments:
      - '@mroca_request_log.reponse_logger'
    tags:
      - { name: bitrix.events.init, module: main, event: OnAfterEpilog, method: handle, sort: 1 }

  Local\Bundles\RequestLogBundle\Service\BitrixBridge\ResponseCacher:
    class: Local\Bundles\RequestLogBundle\Service\BitrixBridge\ResponseCacher
    arguments:
      - '@mroca_request_log.reponse_logger'
      - '@filesystem'
    tags:
      - { name: bitrix.events.init, module: main, event: OnPageStart, method: handle, sort: 1 }