services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Инициализация битриксового события.
  ckeditor_bundle.bitrix_event_handler_init:
    class: Local\Bundles\CkEditorBundle\Services\EventCK
    tags:
      - { name: bitrix.events.init, module: main, event: OnEpilog, method: register, sort: 0 }
