############
# Аннотации
############

parameters:
  annotations.cache_ttl_default: 3600
  enable_annotations: true

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Doctrine\Common\Annotations\AnnotationReader: '@annotations.reader'
  annotation_reader: '@Doctrine\Common\Annotations\AnnotationReader'

  annotations.dummy_registry:
    class: Doctrine\Common\Annotations\AnnotationRegistry
    calls:
      - registerUniqueLoader: ['class_exists']

  annotations.reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    calls:
      - addGlobalIgnoredName: ['required', '@annotations.dummy_registry']

  annotations.filesystem_cache_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - 'annotations'
      - '%annotations.cache_ttl_default%'
      - '%kernel.project_dir%/bitrix/cache/annotations'

  annotations.filesystem_cache:
    class: Symfony\Component\Cache\DoctrineProvider
    arguments:
      - '@annotations.filesystem_cache_adapter'

  annotations.cached_reader:
    class: Doctrine\Common\Annotations\CachedReader
    arguments:
      - '@annotations.reader'
      - '@annotations.filesystem_cache'
      - '%kernel.debug%'
