###########
# Битрикс
###########

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CIBlockElement:
    class: CIBlockElement

  CIBlockSection:
    class: CIBlockSection

   # Новый элемент инфоблока.
  creator.iblock.element:
    class: Local\Services\Bitrix\AddElement
    arguments: ['@Prokl\FrameworkExtensionBundle\Services\TranslitService']

  # Инстанс $APPLICATION
  application:
    class: CMain

  CFile:
    class: CFile
  CUser:
    class: CUser
  CMain:
    class: CMain

  Bitrix\Main\UserTable: ~
  Bitrix\Main\Mail\Event: ~

  # Работа с почтовыми событиями.
  Local\Services\Email\SendNotification:
    class: Local\Services\Email\SendNotification
    arguments: ['@Bitrix\Main\Mail\Event', '@CFile']

  # Загрузчик контента.
  loader.content:
    class: Local\Util\LoaderContent

  # Доступ к bitrix/.settings.php.
  # Параметры: connections.default.host (ключи разделены точками) или connections.
  # См. хэлпер bxConfig
  bx.config:
    class: Local\Util\Config\Manager
