###########
# Битрикс
###########

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CIBlockElement:
    class: CIBlockElement

  CIBlockSection:
    class: CIBlockSection

  # Инстанс $APPLICATION
  application:
    class: CMain

  CFile:
    class: CFile
  CUser:
    class: CUser
  CMain:
    class: CMain

