#########
# Cache
#########
services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # My custom adapter
  app.cache.adapter.filesystem:
    public: true
    autowire: true
    autoconfigure: false
    parent: 'cache.adapter.filesystem'
    tags:
      - { name: 'cache.pool', namespace: 'test_namespace', default_lifetime: 600 }