#####################
# Консольные команды
#####################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Очистка кэша.
  Local\Commands\CacheClear:
    tags:
      - { name: console.command }

  # Создать компонент на базе BBC.
  Local\Commands\Components\NewComponentCommand:
    tags:
      - { name: console.command, command: new:component }

  Local\Commands\Runner\ExampleRunner:
    tags:
      - { name: console.command }

