#########
# Фасады
#########

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Local\Facades\EventDispatcherFacade: ~
  Local\Facades\FilesystemFacade: ~
  Local\Facades\KernelFacade: ~

