####################################
# Абстрактный слой файловой системы
####################################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\Filesystem\Filesystem: '@filesystem'
