####################
# Ресайзер картинок
####################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # GutaResize
  image.resizer:
    class: Local\Util\GutaResize

  # GutaResizeNoUpscale
  image.resizer.no.upscale:
    class: Local\Util\GutaResizeNoUpscale

  # GutaResizeUpscale
  image.resizer.upscale:
    class: Local\Util\GutaResizeUpscale

  # GutaResizeHardCrop
  image.resizer.hard.crop:
    class: Local\Util\GutaResizeHardCrop
