##############
# Сериалайзер
##############

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # json.encoder
  serializer.encode.json.unescaped:
    class: Symfony\Component\Serializer\Encoder\JsonEncode
    arguments:
      - !php/const JSON_UNESCAPED_UNICODE

  json.encoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    arguments:
      - '@serializer.encode.json.unescaped'

  # Нормалайзер объектов.
  object.normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

  # Сериализатор.
  serialize:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      $normalizers:
        - '@object.normalizer'
      $encoders:
        - '@json.encoder'

  Symfony\Component\Serializer\Serializer: '@serialize'
  Symfony\Component\Serializer\SerializerInterface: '@serialize'

  serializer: '@serialize'