#########
# Сессии
#########

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Сессии Symfony.
  session.symfony:
    class: Local\Services\SymfonySession
    tags: ['service.bootstrap']

  Local\Services\SymfonySession: '@session.symfony'

  session.instance:
    class: Symfony\Component\HttpFoundation\Session\Session
    factory: ['@session.symfony', 'session']

  Symfony\Component\HttpFoundation\Session\SessionInterface: '@session.instance'
