##########################
# Вспомогательные сервисы
##########################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Адаптированный Pipeline.
  Prokl\Pipeline\Hub:
    arguments: ['@service_container']

  Prokl\Pipeline\Pipeline:
    arguments: ['@service_container']

  public_logger: '@logger'
