#########################
# Валидация, санитизация
#########################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Санитайзер.
  sanitizer:
    class: Prokl\RequestValidatorSanitizer\Sanitizing\SanitizerService

  Local\Validators\PhoneValidator:
    tags:
      - { name: validator.constraint_validator }

  Local\Validators\EmailValidator:
    tags:
      - { name: validator.constraint_validator }
