#########################
# Валидация, санитизация
#########################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Санитайзер.
  sanitizer:
    class: Prokl\RequestValidatorSanitizer\Sanitizing\SanitizerService

  Prokl\RequestValidatorSanitizer\Sanitizing\SanitizerService: '@sanitizer'
  Prokl\RequestValidatorSanitizer\Sanitizing\SanitizerInterface: '@sanitizer'

  validator:
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: ['@validator.builder', 'getValidator']

  Symfony\Component\Validator\Validator\ValidatorInterface: '@validator'
  validator.mapping.class_metadata_factory: '@validator'

  validator.validator_factory:
    class: Symfony\Component\Validator\ContainerConstraintValidatorFactory
    arguments: []

  validator.builder:
    class: Symfony\Component\Validator\ValidatorBuilder
    factory: ['Symfony\Component\Validator\Validation', 'createValidatorBuilder']
    calls:
      - setConstraintValidatorFactory: ['@validator.validator_factory']

  validator.expression:
    class: Symfony\Component\Validator\Constraints\ExpressionValidator
    tags:
      - { name: validator.constraint_validator, alias: validator.expression }

  validator.email:
    class: Symfony\Component\Validator\Constraints\EmailValidator
    tags:
      - { name: validator.constraint_validator, alias: Symfony\Component\Validator\Constraints\EmailValidator }

  Local\Validators\PhoneValidator:
    tags:
      - { name: validator.constraint_validator }

  Local\Validators\EmailValidator:
    tags:
      - { name: validator.constraint_validator }
