<?php

return     [
    'IBLOCK_ID' => 0,
    'IBLOCK_TYPE' => '',
    'ADD_ELEMENT_CHAIN' => 'Y',
    'ADD_SECTIONS_CHAIN' => 'Y',
    'INCLUDE_IBLOCK_INTO_CHAIN' => 'N',
    'AJAX_MODE' => 'N',
    'AJAX_OPTION_ADDITIONAL' => '',
    'AJAX_OPTION_HISTORY' => 'N',
    'AJAX_OPTION_JUMP' => 'N',
    'AJAX_OPTION_STYLE' => 'Y',
    'BROWSER_TITLE' => '-',
    'CACHE_FILTER' => 'N',
    'CACHE_GROUPS' => 'N',
    'CACHE_TYPE' => 'A',
    'CACHE_TIME' => '',
    'CHECK_DATES' => 'N',
    'DETAIL_ACTIVE_DATE_FORMAT' => 'd.m.Y',
    'DETAIL_DISPLAY_BOTTOM_PAGER' => 'Y',
    'DETAIL_DISPLAY_TOP_PAGER' => 'N',
    'DETAIL_FIELD_CODE' => [
        'ID',
        'PREVIEW_TEXT',
        'PREVIEW_PICTURE',
        'DETAIL_PICTURE',
        'ACTIVE_FROM',
    ],
    'DETAIL_PAGER_SHOW_ALL' => 'Y',
    'DETAIL_PAGER_TEMPLATE' => '',
    'DETAIL_PAGER_TITLE' => 'Страница',
    'DETAIL_PROPERTY_CODE' => [
        'ID',
        'PREVIEW_TEXT',
        'PREVIEW_PICTURE',
        'DETAIL_PICTURE',
        'ACTIVE_FROM',
        'CANONICAL_URL',
    ],
    'DETAIL_SET_CANONICAL_URL' => 'N',
    'DISPLAY_BOTTOM_PAGER' => 'Y',
    'DISPLAY_DATE' => 'Y',
    'DISPLAY_NAME' => 'Y',
    'DISPLAY_PICTURE' => 'Y',
    'DISPLAY_PREVIEW_TEXT' => 'Y',
    'DISPLAY_TOP_PAGER' => 'N',
    'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
    'LIST_ACTIVE_DATE_FORMAT' => 'd.m.Y',
    'LIST_FIELD_CODE' => ['ID', 'NAME', 'PREVIEW_TEXT', 'PREVIEW_PICTURE', 'H1'],
    'LIST_PROPERTY_CODE' => ['', 'TYPE'],
    'MEDIA_PROPERTY' => '',
    'MESSAGE_404' => '',
    'META_DESCRIPTION' => '-',
    'META_KEYWORDS' => '-',
    'NEWS_COUNT' => '20',
    'PAGER_BASE_LINK_ENABLE' => 'N',
    'PAGER_DESC_NUMBERING' => 'N',
    'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
    'PAGER_SHOW_ALL' => 'N',
    'PAGER_SHOW_ALWAYS' => 'N',
    'PAGER_TEMPLATE' => '.default',
    'PAGER_TITLE' => '',
    'PREVIEW_TRUNCATE_LEN' => '',
    'SEF_FOLDER' => '',
    'SEF_MODE' => 'Y',
    'SEF_URL_TEMPLATES' => ['detail' => '#ELEMENT_CODE#/', 'news' => '', 'section' => ''],
    'SET_LAST_MODIFIED' => 'N',
    'SET_STATUS_404' => 'Y',
    'SET_TITLE' => 'N',
    'SHOW_404' => 'Y',
    'SLIDER_PROPERTY' => '',
    'SORT_BY1' => 'SORT',
    'SORT_BY2' => 'ACTIVE_FROM',
    'SORT_ORDER1' => 'ASC',
    'SORT_ORDER2' => 'DESC',
    'STRICT_SECTION_CHECK' => 'N',
    'TEMPLATE_THEME' => 'blue',
    'USE_CATEGORIES' => 'N',
    'USE_FILTER' => 'N',
    'USE_PERMISSIONS' => 'N',
    'USE_RATING' => 'N',
    'USE_REVIEW' => 'N',
    'USE_RSS' => 'N',
    'USE_SEARCH' => 'N',
    'USE_SHARE' => 'N',
    'H1_PROPERTY' => '',
];
