foo_route:
  path: /foo
  controller: 'Local\Router\Examples\DummyController::action'

foo_placeholder_route:
  path: /foo/{id}
  controller: 'Local\Router\Examples\DummyController::loadAction'
  requirements:
    id: "[0-9]+"

remove_trailing_slash:
  path: /{url}
  controller: 'Local\Router\Examples\DummyController::loadAction'

index:
  path: /
  controller: 'Local\Router\Supply\UtilRoutes::indexRoute'

not-found:
  path: /{url}
  controller: 'Local\Router\Supply\UtilRoutes::notFound'
