services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  model_bundle.factory.elements:
    public: true
    class: Local\Bundles\ModelBundle\Services\Factories\ModelElementFactory
    arguments: [!tagged_locator { tag: 'iblock.element.model', index_by: 'key' }, '@CIBlockElement']

  Local\Bundles\ModelBundle\Services\Factories\ModelElementFactory: '@model_bundle.factory.elements'

  model_bundle.factory.sections:
    public: true
    class: Local\Bundles\ModelBundle\Services\Factories\ModelSectionFactory
    arguments: [!tagged_locator { tag: 'iblock.section.model', index_by: 'key' }, '@CIBlockSection']

  Local\Bundles\ModelBundle\Services\Factories\ModelSectionFactory: '@model_bundle.factory.sections'